### ISSUE TITLE
[segmentation fault (core dumped) ]cannot execute after compilation

### ISSUE THREAD

**Issue by Lazxs** [vanAken/CarND-Path-Planning-Project#2]
After following the Build Instructions, I ran the command "./path_planning" and it turned out to be "segmentation fault (core dumped)". How to solve it?

By the way, during compilation, there goes a warning of warning: " ‘Frenet’ has a field ‘Frenet::s_x’ whose type uses the anonymous namespace".

Thanks !!!!

**Comment by vanAken** [comment]
I got no idea, based on your rare information.

**Comment by vanAken** [comment]
due no more info closed
